#!/usr/bin/env bash
#
# Runs every golden generator and asserts each committed golden comes back byte for byte.
#
# WHY THIS EXISTS
#
# The goldens under src/test/resources/golden/ are generated by three node scripts that
# run the original HTML app's own code. Nothing checked that regenerating them was a
# no-op, and on 2026-09-09 that gap bit: original-loadstate.js --all globbed the fixture
# directory and swept in engine-scenarios.json, which is geometry input rather than a save
# file, so it wrote an 18-line empty room over the 2,032-line engine golden. The suite
# stayed green, because the Java tests read whatever the golden says. The only repair was
# `git checkout`. See the SAVE_FIXTURES comment in original-loadstate.js.
#
# This script is the thing that would have caught it, and it is what to run after touching
# a generator, a fixture, or anything either of them reads.
#
# It is NON-DESTRUCTIVE. The goldens and fixtures are snapshotted first, the generators
# run over the real tree, every file is compared against the snapshot, and the snapshot is
# put back whatever the result. So a failing run leaves the working tree exactly as it
# found it, and this is a check rather than a way to regenerate. To regenerate, run the
# generator you actually mean.
#
# WHAT IT DELIBERATELY DOES NOT RUN
#
# original-engine.js --gen, which writes the fixture rather than the golden, and defaults
# to 200 scenarios where the committed fixture holds 250. Running it here would rewrite
# the input the engine golden is derived from and the comparison would be meaningless.
#
# USAGE
#   bash tools/golden/verify-goldens.sh

set -uo pipefail

REPO=$(cd "$(dirname "$0")/../.." && pwd)
GOLDEN_DIR="$REPO/src/test/resources/golden"
FIXTURE_DIR="$REPO/src/test/resources/fixtures"

command -v node >/dev/null 2>&1 || { echo "verify-goldens: node is not on PATH" >&2; exit 2; }
[ -d "$GOLDEN_DIR" ]  || { echo "verify-goldens: no $GOLDEN_DIR" >&2; exit 2; }
[ -d "$FIXTURE_DIR" ] || { echo "verify-goldens: no $FIXTURE_DIR" >&2; exit 2; }

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

cp -a "$GOLDEN_DIR"  "$WORK/golden"
cp -a "$FIXTURE_DIR" "$WORK/fixtures"

# The snapshot is what the restore reads from, so refuse to go any further if it did not
# copy. Without this, a failed cp followed by the restore below would delete goldens.
snap_golden=$(find "$WORK/golden" -maxdepth 1 -name '*.json' | wc -l)
live_golden=$(find "$GOLDEN_DIR"  -maxdepth 1 -name '*.json' | wc -l)
if [ "$snap_golden" -eq 0 ] || [ "$snap_golden" -ne "$live_golden" ]; then
  echo "verify-goldens: snapshot is incomplete ($snap_golden of $live_golden); refusing to run" >&2
  exit 2
fi
echo "snapshotted $snap_golden golden file(s)"

cd "$REPO"
gen_failed=0
for gen in \
  "tools/golden/original-engine.js --run" \
  "tools/golden/original-3d.js --run" \
  "tools/golden/original-loadstate.js --all" \
  "tools/golden/original-loadstate.js --numbers"
do
  echo
  echo "--- node $gen"
  # shellcheck disable=SC2086
  node $gen || { echo "verify-goldens: generator failed: $gen" >&2; gen_failed=1; }
done

echo
failures=0

# Every committed golden must come back unchanged.
for snap in "$WORK/golden"/*.json; do
  name=$(basename "$snap")
  live="$GOLDEN_DIR/$name"
  if [ ! -f "$live" ]; then
    echo "  GONE      $name  (a generator deleted it)"
    failures=$((failures + 1))
  elif cmp -s "$snap" "$live"; then
    echo "  same      $name"
  else
    echo "  CHANGED   $name  ($(wc -c < "$snap") bytes -> $(wc -c < "$live") bytes)"
    failures=$((failures + 1))
  fi
done

# And nothing new may appear: a golden with no committed copy means a generator is writing
# somewhere nobody is checking.
for live in "$GOLDEN_DIR"/*.json; do
  name=$(basename "$live")
  [ -f "$WORK/golden/$name" ] || { echo "  NEW       $name  (written by a generator, not committed)"; failures=$((failures + 1)); }
done

# Fixtures are inputs. A generator that writes one has rewritten the question to match its
# own answer, which is exactly the shape of the bug this script exists for.
for snap in "$WORK/fixtures"/*.json; do
  name=$(basename "$snap")
  live="$FIXTURE_DIR/$name"
  if [ ! -f "$live" ] || ! cmp -s "$snap" "$live"; then
    echo "  FIXTURE   $name  (a generator wrote to an input file)"
    failures=$((failures + 1))
  fi
done

# Restore, always, so a failed run leaves the tree as it was found.
for snap in "$WORK/golden"/*.json; do
  cp -a "$snap" "$GOLDEN_DIR/$(basename "$snap")"
done
for live in "$GOLDEN_DIR"/*.json; do
  name=$(basename "$live")
  [ -f "$WORK/golden/$name" ] || rm -f "$live"
done
for snap in "$WORK/fixtures"/*.json; do
  cp -a "$snap" "$FIXTURE_DIR/$(basename "$snap")"
done

echo
if [ "$gen_failed" -ne 0 ]; then
  echo "FAIL: a generator exited non-zero (see above). Goldens restored."
  exit 1
fi
if [ "$failures" -ne 0 ]; then
  echo "FAIL: $failures file(s) did not reproduce. Goldens restored, so the tree is unchanged."
  echo "If a fixture really did change, regenerate deliberately and commit the new golden."
  exit 1
fi
echo "OK: all $snap_golden golden file(s) reproduce byte for byte."
