/*
 * InvMgr Android host layer: shared declarations.
 *
 * WHAT THIS FILE IS FOR
 *
 * Everything in native/ exists to sit between Android and the JavaFX code compiled into
 * libsubstrate.so. See docs/PLAN-M6.5B-HOST-LAYER.md. The short version: OpenJFX already
 * contains a complete Android backend and needs nothing from us except a window, a screen
 * density, and input. Our job is to hand it those and stay out of the way.
 *
 * WHY WE DECLARE OPENJFX'S FUNCTIONS OURSELVES RATHER THAN INCLUDING A HEADER
 *
 * The obvious move is to include Gluon's grandroid.h, which declares them. Do not.
 * That header does not merely declare them, it DEFINES them, weak and empty:
 *
 *     void __attribute__((weak)) androidJfx_setDensity(float d) {}
 *
 * Those exist so Substrate's own C still links when JavaFX is absent. Pulling them in here
 * would give this translation unit its own empty copies, and whether the real ones win
 * would come down to link order. The failure mode is the worst kind: it builds, it runs,
 * and nothing ever reaches JavaFX.
 *
 * So the prototypes below are written out by hand. They must match what
 * libglass_monocle.a actually exports. Verify with:
 *
 *     nm --defined-only .../libglass_monocle.a | grep androidJfx_
 */

#ifndef INVMGR_HOST_H
#define INVMGR_HOST_H

#include <jni.h>
#include <stdbool.h>
#include <android/native_window.h>

/* ---- What OpenJFX gives us -------------------------------------------------------- */

/* Hand JavaFX the window to draw into. NULL means the window is gone. */
extern void androidJfx_setNativeWindow(ANativeWindow *window);

/* Screen density, so JavaFX can work in logical pixels. */
extern void androidJfx_setDensity(float density);

/*
 * One batch of touch points.
 *
 * `actions` holds JavaFX touch states, not Android ones, so run each through
 * to_jfx_touch_action first. `primary` is the index of the point that the gesture is
 * really about, or -1 when a single finger has just been lifted.
 */
extern void androidJfx_gotTouchEvent(int count, int *actions, int *ids,
                                     int *xs, int *ys, int primary);

extern void androidJfx_gotKeyEvent(int action, int key, jchar *chars, int count, int mods);

extern void androidJfx_requestGlassToRedraw(void);

/*
 * Android to JavaFX conversion, also from OpenJFX. Using this rather than writing our own
 * keeps the mapping in one place, and it is the same place JavaFX reads it from.
 *
 * OpenJFX has two more of these, to_jfx_key_action and to_linux_keycode, and the key path
 * here deliberately calls NEITHER. invmgr_input.c says why, at length: they produce the
 * wrong kind of value for what androidJfx_gotKeyEvent actually wants. They are not
 * declared here, so that reaching for them means reading that comment first.
 */
extern int to_jfx_touch_action(int androidAction);

/* JavaFX's own touch states. Values confirmed from com.sun.glass.events.TouchEvent. */
#define INVMGR_TOUCH_PRESSED  811
#define INVMGR_TOUCH_MOVED    812
#define INVMGR_TOUCH_RELEASED 813
#define INVMGR_TOUCH_STILL    814

/* ---- What the native image gives us ------------------------------------------------ */

/*
 * Runs the application. Generated by native-image from com.modcritic.invmgr.Launcher.
 * It does not return while the app is alive, so it must be called from a thread that can
 * afford to block. Confirmed present with:
 *
 *     nm --defined-only com.modcritic.invmgr.launcher.o | grep run_main
 */
extern int *run_main(int argc, char *argv[]);

/* ---- Shared between our own files -------------------------------------------------- */

extern JavaVM *invmgr_vm;

/* The Activity's class, as a global reference. NULL before onCreate has run. */
extern jclass invmgr_activity_class;

/*
 * Whether the surface may be drawn into right now.
 *
 * Android takes the native window away when the app goes to the background. Drawing after
 * that point does not crash, it just makes libEGL log an error for every frame forever, so
 * the EGL calls are gated on this. Set in invmgr_surface.c, read there too.
 */
bool invmgr_surface_is_valid(void);

/* Attaches the calling thread to the Dalvik VM and returns its JNIEnv, or NULL. */
JNIEnv *invmgr_attach_current_thread(void);

/* Sends stdout and stderr to logcat. Called once, from JNI_OnLoad. */
int invmgr_start_logger(const char *tag);

#define INVMGR_LOG_TAG "InvMgr"

#endif /* INVMGR_HOST_H */
